# Pythonイメージの取得
FROM python:3.7.9-slim-buster
# ワーキングディレクトリの指定
WORKDIR /app
COPY ./requirements.txt ./
COPY ./line_magic/requirements.txt ./line_magic_requirements.txt
# 機械学習関連のライブラリを無理やり挿入
RUN apt-get update && apt-get install -y\
    build-essential \
    gfortran \
    python3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install https://www.piwheels.org/simple/numpy/numpy-1.19.4-cp37-cp37m-linux_armv7l.whl
RUN pip install https://www.piwheels.org/simple/scipy/scipy-1.5.4-cp37-cp37m-linux_armv7l.whl
RUN pip install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.3.0/tensorflow-2.3.0-cp37-none-linux_armv7l.whl
RUN pip install -r requirements.txt
RUN pip install -r line_magic_requirements.txt
# .NudeNet/lite_classifier Checkpointのダウンロード
RUN python3 -c "from nudenet import NudeClassifierLite;x = NudeClassifierLite()"
# モジュールを揃える
COPY . .
# 起動環境設定
EXPOSE 1204
ENTRYPOINT [ "gunicorn", "main:app" ]
CMD [ "-c", "gunicorn_config.py" ]